<a href="https://colab.research.google.com/github/RORRE-ERROR/data-science-toolkit/blob/main/Week_3%2C_Tutorial_3%2C_24209805.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import random

In [ ]:
# 1.
a = [[1, 2], [3, 4]]
print(a)

[[1, 2], [3, 4]]


In [ ]:
# 2.
b = np.random.rand(3, 4)
print(b)

[[0.16008165 0.56902435 0.35486153 0.52710972]
 [0.3154108  0.51048441 0.47603434 0.30502532]
 [0.2563551  0.70186171 0.22739508 0.20088064]]


In [ ]:
# 3.
c1 = np.ones(5)
c2 = np.zeros(5)
print(c1)
print(c2)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [ ]:
# 4.
d = np.random.rand(6, 3)
print(d)
transpose_d = d.T
print(transpose_d)

[[0.4675353  0.11584912 0.12215321]
 [0.24835109 0.21796942 0.33924852]
 [0.71076729 0.98017822 0.55434749]
 [0.21260583 0.65170326 0.92692684]
 [0.48584783 0.4025277  0.70590732]
 [0.14817869 0.24411136 0.19321012]]
[[0.4675353  0.24835109 0.71076729 0.21260583 0.48584783 0.14817869]
 [0.11584912 0.21796942 0.98017822 0.65170326 0.4025277  0.24411136]
 [0.12215321 0.33924852 0.55434749 0.92692684 0.70590732 0.19321012]]


In [ ]:
# 5.
n = 3
p = 4
m = 5
array1 = np.random.rand(n, p)
array2 = np.random.rand(p, m)
print("Array 1 (n x p):")
print(array1)
print("Array  (p x m):")
print(array2)
print("Dot product of Array 1 and Array 2:")
dot_product = np.dot(array1, array2)

print(dot_product)

Array 1 (n x p):
[[0.50881271 0.68789661 0.81624741 0.51191116]
 [0.302076   0.21586173 0.62726446 0.21048751]
 [0.52383739 0.05764166 0.08195118 0.94075408]]
Array  (p x m):
[[0.62659375 0.93423274 0.19703634 0.06938178 0.81629314]
 [0.32585136 0.28668573 0.0732033  0.53612915 0.09878254]
 [0.0848408  0.45962717 0.07751273 0.1093369  0.34507992]
 [0.76245531 0.04411601 0.69088416 0.94826382 0.31219859]]
Dot product of Array 1 and Array 2:
[[1.00253137 1.0703126  0.56755178 0.97877655 0.92478103]
 [0.47332271 0.64168743 0.26936521 0.40486917 0.55007621]
 [1.0712516  0.58508039 0.76373891 0.96829149 0.75528066]]
